### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JunCEEE**

### CODE REVIEW

**Comment by CFGrote** [comment]
hi juncheng, all good, just want to make sure you included shervin's edits of the readme?

**Comment by JunCEEE** [comment]
> hi juncheng, all good, just want to make sure you included shervin's edits of the readme?

Not yet. Actually, I don't know where to get it.

**Comment by CFGrote** [comment]
@shervin86, where can @juncheng find your readme edits for simex?

**Comment by shervin86** [comment]
in the branch "shervin"

**Comment by JunCEEE** [comment]
Thanks. @shervin86 When you are ready, could you make a pull request?

**Pull request merged**
