### PR TITLE
add total Intensity dump function

### PR DESCRIPTION
**Pull request by JunCEEE**

### CODE REVIEW

**Review by CFGrote — CHANGES_REQUESTED** [review]
Hi Juncheng.
Is there not something like this in prop_diagnostics.py ?

Also, please add unittests.

**Comment by JunCEEE** [comment]
There are only some plot functions in `prop_diagnostics.py `. No way to dump the data into a numpy array.

I will add tests later. Thanks.

**Comment by CFGrote** [comment]
Where are we?

**Comment by JunCEEE** [comment]
- Added unit test
- renamed dumpTotalPower to numpyTotalPower

Hi @CFGrote,

I noticed there were `dumpToFile` functions defined in `AbstractAnalysis.py`. But that is not what I need. I just need the functions to be able to export the data into numpy array. So I renamed the function name to `numpyTotalPower` to avoid misunderstanding.

It should be now ready to be merged.

**Pull request merged**
