### PR TITLE
Gapd

### PR DESCRIPTION
**Pull request by CFGrote**

### CODE REVIEW

**Comment by CFGrote** [comment]
@ejcjason , can you fix these conflicts. I cannot get the Ci pass without this.

**Comment by JunCEEE** [comment]
Yes, I will check that.

**Comment by JunCEEE** [comment]
@CFGrote  I can fix the conflicts.
There is a decision to make before merging:
for `xrayDB`, do we use `https://github.com/xraypy/XrayDB/archive/4.2.zip` in this PR fix or use the `xraydb ` module added to [requirements.txt](https://github.com/eucall-software/simex_platform/blob/develop/requirements.txt#L19) in your recent commit?

PS: the hdf5 data for testing likely needs to be cleaned up, data like [prop_out_0000001.h5](https://github.com/eucall-software/simex_platform/tree/master/Tests/python/unittest/TestFiles/prop_out_0000001.h5) cannot be read by `h5ls` and `h5dump` tested with h5py2.10

**Comment by CFGrote** [comment]
I just realize that some commits of this PR are already in #179. Let's finish that one first and then see about the remainders here.

**Pull request merged**
